export const GET_AUTH_TOKEN_REQUEST = "GET_AUTH_TOKEN_REQUEST";
export const GET_AUTH_TOKEN_SUCCESS = "GET_AUTH_TOKEN_SUCCESS";
export const GET_AUTH_TOKEN_FAILED = "GET_AUTH_TOKEN_FAILED";

export const REMOVE_AUTH_TOKEN_REQUEST = "REMOVE_AUTH_TOKEN_REQUEST";
export const REMOVE_AUTH_TOKEN_SUCCESS = "REMOVE_AUTH_TOKEN_SUCCESS";
export const REMOVE_AUTH_TOKEN_FAILED = "REMOVE_AUTH_TOKEN_FAILED";

export const GET_USER_DETAILS_REQUEST = "GET_USER_DETAILS_REQUEST";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAILED = "GET_USER_DETAILS_FAILED";
