export const GET_COMMITTEE_DETAILS_REQUEST = "GET_COMMITTEE_DETAILS_REQUEST";
export const GET_COMMITTEE_DETAILS_SUCCESS = "GET_COMMITTEE_DETAILS_SUCCESS";
export const GET_COMMITTEE_DETAILS_FAILED = "GET_COMMITTEE_DETAILS_FAILED";

export const ADD_COMMITTEE_REQUEST = "ADD_COMMITTEE_REQUEST";
export const ADD_COMMITTEE_SUCCESS = "ADD_COMMITTEE_SUCCESS";
export const ADD_COMMITTEE_FAILED = "ADD_COMMITTEE_FAILED";
export const RESET_ADD_COMMITTEE = "RESET_ADD_COMMITTEE";

export const GET_ALL_COMMITTEES_REQUEST = "GET_ALL_COMMITTEES_REQUEST";
export const GET_ALL_COMMITTEES_SUCCESS = "GET_ALL_COMMITTEES_SUCCESS";
export const GET_ALL_COMMITTEES_FAILED = "GET_ALL_COMMITTEES_FAILED";

export const DELETE_COMMITTEE_REQUEST = "DELETE_COMMITTEE_REQUEST";
export const DELETE_COMMITTEE_SUCCESS = "DELETE_COMMITTEE_SUCCESS";
export const DELETE_COMMITTEE_FAILED = "DELETE_COMMITTEE_FAILED";

export const GET_UPDATE_COMMITTEE_REQUEST = "GET_UPDATE_COMMITTEE_REQUEST";
export const GET_UPDATE_COMMITTEE_SUCCESS = "GET_UPDATE_COMMITTEE_SUCCESS";
export const GET_UPDATE_COMMITTEE_FAILED = "GET_UPDATE_COMMITTEE_FAILED";
export const GET_UPDATE_COMMITTEE_RESET = "GET_UPDATE_COMMITTEE_RESET";

export const UPDATE_COMMITTEE_REQUEST = "UPDATE_COMMITTEE_REQUEST";
export const UPDATE_COMMITTEE_SUCCESS = "UPDATE_COMMITTEE_SUCCESS";
export const UPDATE_COMMITTEE_FAILED = "UPDATE_COMMITTEE_FAILED";
