export const GET_ALL_DEPARTMENTS_REQUEST = "GET_ALL_DEPARTMENTS_REQUEST";
export const GET_ALL_DEPARTMENTS_SUCCESS = "GET_ALL_DEPARTMENTS_SUCCESS";
export const GET_ALL_DEPARTMENTS_FAILED = "GET_ALL_DEPARTMENTS_FAILED";

export const GET_DEPARTMENT_DETAILS_REQUEST = "GET_DEPARTMENT_DETAILS_REQUEST";
export const GET_DEPARTMENT_DETAILS_SUCCESS = "GET_DEPARTMENT_DETAILS_SUCCESS";
export const GET_DEPARTMENT_DETAILS_FAILED = "GET_DEPARTMENT_DETAILS_FAILED";
