export const GET_ALL_MEETINGS_REQUEST = "GET_ALL_MEETINGS_REQUEST";
export const GET_ALL_MEETINGS_SUCCESS = "GET_ALL_MEETINGS_SUCCESS";
export const GET_ALL_MEETINGS_FAILED = "GET_ALL_MEETINGS_FAILED";

export const GET_MEETING_DETAILS_REQUEST = "GET_MEETING_DETAILS_REQUEST";
export const GET_MEETING_DETAILS_SUCCESS = "GET_MEETING_DETAILS_SUCCESS";
export const GET_MEETING_DETAILS_FAILED = "GET_MEETING_DETAILS_FAILED";

export const ADD_MEETING_REQUEST = "ADD_MEETING_REQUEST";
export const ADD_MEETING_SUCCESS = "ADD_MEETING_SUCCESS";
export const ADD_MEETING_FAILED = "ADD_MEETING_FAILED";

export const GET_UPDATE_MEETING_REQUEST = "GET_UPDATE_MEETING_REQUEST";
export const GET_UPDATE_MEETING_SUCCESS = "GET_UPDATE_MEETING_SUCCESS";
export const GET_UPDATE_MEETING_FAILED = "GET_UPDATE_MEETING_FAILED";
export const GET_UPDATE_MEETING_RESET = "GET_UPDATE_MEETING_RESET";

export const UPDATE_MEETING_REQUEST = "UPDATE_MEETING_REQUEST";
export const UPDATE_MEETING_SUCCESS = "UPDATE_MEETING_SUCCESS";
export const UPDATE_MEETING_FAILED = "UPDATE_MEETING_FAILED";

export const DELETE_MEETING_REQUEST = "DELETE_MEETING_REQUEST";
export const DELETE_MEETING_SUCCESS = "DELETE_MEETING_SUCCESS";
export const DELETE_MEETING_FAILED = "DELETE_MEETING_FAILED";
