export const GET_ALL_MEMBERS_REQUEST = "GET_ALL_MEMBERS_REQUEST";
export const GET_ALL_MEMBERS_SUCCESS = "GET_ALL_MEMBERS_SUCCESS";
export const GET_ALL_MEMBERS_FAILED = "GET_ALL_MEMBERS_FAILED";

export const GET_SEARCH_MEMBERS_REQUEST = "GET_SEARCH_MEMBERS_REQUEST";
export const GET_SEARCH_MEMBERS_SUCCESS = "GET_SEARCH_MEMBERS_SUCCESS";
export const GET_SEARCH_MEMBERS_FAILED = "GET_SEARCH_MEMBERS_FAILED";

export const ADD_MEMBER_REQUEST = "ADD_MEMBER_REQUEST";
export const ADD_MEMBER_SUCCESS = "ADD_MEMBER_SUCCESS";
export const ADD_MEMBER_FAILED = "ADD_MEMBER_FAILED";

export const DELETE_MEMBER_REQUEST = "DELETE_MEMBER_REQUEST";
export const DELETE_MEMBER_SUCCESS = "DELETE_MEMBER_SUCCESS";
export const DELETE_MEMBER_FAILED = "DELETE_MEMBER_FAILED";

export const GET_UPDATE_MEMBER_REQUEST = "GET_UPDATE_MEMBER_REQUEST";
export const GET_UPDATE_MEMBER_SUCCESS = "GET_UPDATE_MEMBER_SUCCESS";
export const GET_UPDATE_MEMBER_FAILED = "GET_UPDATE_MEMBER_FAILED";

export const UPDATE_MEMBER_REQUEST = "UPDATE_MEMBER_REQUEST";
export const UPDATE_MEMBER_SUCCESS = "UPDATE_MEMBER_SUCCESS";
export const UPDATE_MEMBER_FAILED = "UPDATE_MEMBER_FAILED";
