export const GET_SEARCH_RESULT_REQUEST = "GET_SEARCH_RESULT_REQUEST";
export const GET_SEARCH_RESULT_SUCCESS = "GET_SEARCH_RESULT_SUCCESS";
export const GET_SEARCH_RESULT_FAILED = "GET_SEARCH_RESULT_FAILED";
